INSERT INTO counties (countyid, county) VALUES (1, 'Hertfordshire')
,(2, 'Bedfordshire')
,(3, 'West Midlands')
,(4, 'Worcestershire')
,(5, 'Warwickshire')
,(6, 'Staffordshire')
,(7, 'Leicestershire')
,(8, 'Somerset')
,(9, 'Gloucestershire')
,(10, 'Wiltshire')
,(11, 'Dorset')
,(12, 'Lancashire')
,(13, 'North Yorkshire')
,(14, 'West Yorkshire')
,(15, 'Hampshire')
,(16, 'Greater Manchester')
,(17, 'East Sussex')
,(18, 'West Sussex')
,(19, 'Greater London')
,(20, 'Kent')
,(21, 'Bristol')
,(22, 'Cumbria')
,(23, 'Northumberland')
,(24, 'Cambridgeshire')
,(25, 'Essex')
,(26, 'Norfolk')
,(27, 'Suffolk')
,(28, 'Cheshire')
,(29, 'Merseyside')
,(30, 'Surrey')
,(31, 'Northamptonshire')
,(32, 'Shropshire')
,(33, 'Derbyshire')
,(34, 'Nottinghamshire')
,(35, 'County Durham')
,(36, 'Tyne and Wear')
,(37, 'South Yorkshire')
,(38, 'Lincolnshire')
,(39, 'East Riding of Yorkshire')
,(40, 'Devon')
,(41, 'City of London')
,(42, 'Cornwall')
,(43, 'Herefordshire')
,(44, 'Oxfordshire')
,(45, 'Berkshire')
,(46, 'Buckinghamshire')
,(47, 'Rutland')
,(48, 'Isle of Wight')
